### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by app-src** [sachinrwt/Dice#1]
Stimulate rolling animation by changing images in a fixed interval a few times before stopping at one side. Wait time = excitement
even better if dice are rolled one by one for each player, automatically but one by one. Cool UI though, mera portfolio design krdo next.

**Comment by sachinrwt** [comment]
Really appreciate your suggestion . I'll definitely work on it . only paid work (evil laugh) jk , i'll love to

**Comment by app-src** [comment]
👀

**Comment by sachinrwt** [comment]
Did some changes, not as you mentioned but added some animation !! and really appreciated your suggestion
